version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor: win/default

    steps:
      - checkout

      - run:
          name: "dotnet publish"
          command: |
            dotnet publish -o ./VehicleStateDesignPattern/tempArtifacts ./VehicleStateDesignPattern/VehicleStateDesignPattern/VehicleStateDesignPattern.csproj
            apt-get update
            apt-get install zip -y
            cd VehicleStateDesignPattern/tempArtifacts
            zip -r VehicleStateDesignPattern .
            mkdir artifacts
            mv VehicleStateDesignPattern artifacts

      - store_artifacts:
          path: ./VehicleStateDesignPattern/tempArtifacts/artifacts

workflows:
  version: 2.1
  build:
    jobs:
      - approve-build:
          type: approval
          # filters:
          #   branches:
          #     only: develop

      - build:
          requires:
            - approve-build
