version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  test:
    executor: win/default

    steps:
      - checkout

      - run:
          name: "dotnet publish"
          command: |
            dotnet test DepaTest

  build:
    executor: win/default

    steps:
      - checkout

      - run:
          name: "dotnet publish"
          command: |
            dotnet publish -o ./VehicleStateDesignPattern/tempArtifacts ./VehicleStateDesignPattern/VehicleStateDesignPattern/VehicleStateDesignPattern.csproj
            cd VehicleStateDesignPattern/tempArtifacts
            Compress-Archive . VehicleStateDesignPattern.zip
            mkdir artifacts
            mv VehicleStateDesignPattern.zip artifacts

      - store_artifacts:
          path: ./VehicleStateDesignPattern/tempArtifacts/artifacts

workflows:
  version: 2.1
  build:
    jobs:
      - test

      - approve-build:
          type: approval
          requires:
            - test
          # filters:
          #   branches:
          #     only: develop

      - build:
          requires:
            - approve-build
